/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal app development. It is checked in here so
// the extracted CodeMode workspace typechecks immediately after cloning.
