import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import { describe, expect, it } from 'vitest'

import type { RuntimeApproval, RuntimePolicySnapshot } from '../types.js'
import { renderZflowResult, runZflowWorkflow } from './zflow-workflow.js'

const policy: RuntimePolicySnapshot = {
  mode: 'APPROVED_EXECUTION',
  allowNetwork: false,
  allowReadOnlyNetwork: true,
  allowShell: false,
  allowWrites: true,
  allowGitHubWrites: true,
  protectedPaths: ['node_modules', 'dist', 'coverage'],
  noisyDirs: [],
}

const approval: RuntimeApproval = {
  ticketId: 'Z-001',
  approvedBy: 'operator',
  scopes: ['file:write', 'github:write'],
}

function makeWorkspace(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'codemind-zflow-'))
}

const request = {
  name: 'Zflow preview',
  mode: 'prepare-pr' as const,
  reason: 'Prepare approved workflow output',
  rollbackNote: 'Delete generated file',
  files: [{ path: 'src/generated.ts', content: 'export const generated = true\n' }],
  repository: 'JLPARTIN/CodeMind',
  baseBranch: 'main',
  headBranch: 'zflow-generated',
  title: 'Zflow generated change',
  body: 'Generated by zflow.',
  policy,
  approval,
}

describe('runZflowWorkflow', () => {
  it('previews local changes without writing files', async () => {
    const workspace = makeWorkspace()
    const result = await runZflowWorkflow(
      {
        ...request,
        mode: 'preview-only',
      },
      workspace,
    )

    expect(result.mode).toBe('preview-only')
    expect(result.localOutput).toBe('completed')
    expect(result.prOutput).toBeNull()
    expect(result.recoveryOutput).toContain('CodeMind recovery change ledger')
    expect(result.rollbackOutput).toContain('Rollback plan: Recover Zflow preview')
    expect(fs.existsSync(path.join(workspace, 'src/generated.ts'))).toBe(false)
  })

  it('prepares fake-client PR and collaboration dry-run output', async () => {
    const workspace = makeWorkspace()
    const result = await runZflowWorkflow(request, workspace)

    expect(result.mode).toBe('prepare-pr')
    expect(result.localOutput).toBe('completed')
    expect(result.prOutput).toContain('CodeMind GitHub PR creation')
    expect(result.prOutput).toContain('Outcome: DRY_RUN')
    expect(result.collaborationOutput).toContain('CodeMind PR collaboration')
    expect(result.collaborationOutput).toContain('Outcome: DRY_RUN')
    expect(result.recoveryOutput).toContain('Changes: 1')
    expect(result.recoveryOutput).toContain('src/generated.ts')
    expect(result.rollbackOutput).toContain('Delete generated file')
    expect(fs.existsSync(path.join(workspace, 'src/generated.ts'))).toBe(false)
  })

  it('renders zflow result with recovery sections', async () => {
    const result = await runZflowWorkflow(request, makeWorkspace())
    const output = renderZflowResult(result)

    expect(output).toContain('CodeMind zflow workflow')
    expect(output).toContain('Mode: prepare-pr')
    expect(output).toContain('CodeMind recovery change ledger')
    expect(output).toContain('Rollback plan: Recover Zflow preview')
    expect(output).toContain('no live GitHub mutation by default')
  })
})
