import { describe, expect, it } from 'vitest'

import type { RuntimeApproval, RuntimePolicySnapshot } from '../types.js'
import { FakeGitHubPrCreationClient } from './fake-github-pr-creation-client.js'
import { executeGitHubPrCreation, renderGitHubPrCreationResult } from './github-pr-creation.js'

const policy: RuntimePolicySnapshot = {
  mode: 'APPROVED_EXECUTION',
  allowNetwork: false,
  allowShell: false,
  allowWrites: false,
  allowGitHubWrites: true,
  protectedPaths: [],
  noisyDirs: [],
}

const approval: RuntimeApproval = {
  ticketId: 'GITHUB-X-001',
  approvedBy: 'operator',
  scopes: ['github:write'],
}

const request = {
  repository: 'JLPARTIN/CodeMind',
  baseBranch: 'main',
  headBranch: 'phase-x-generated',
  title: 'Phase X generated PR',
  body: 'Generated by Phase X fake client.',
  reason: 'Create approved draft PR',
  dryRun: false,
  files: [{ path: 'docs/generated.md', content: '# Generated\n' }],
}

describe('executeGitHubPrCreation', () => {
  it('dry-runs without client operations', async () => {
    const client = new FakeGitHubPrCreationClient()
    const result = await executeGitHubPrCreation(
      { ...request, dryRun: true },
      policy,
      approval,
      client,
    )

    expect(result.outcome).toBe('DRY_RUN')
    expect(result.operations).toHaveLength(3)
    expect(client.operations).toHaveLength(0)
  })

  it('uses the fake client when approved', async () => {
    const client = new FakeGitHubPrCreationClient()
    const result = await executeGitHubPrCreation(request, policy, approval, client)

    expect(result.outcome).toBe('CREATED')
    expect(result.pullRequestUrl).toContain('phase-x-generated')
    expect(client.operations.map((operation) => operation.type)).toEqual([
      'createBranch',
      'commitFiles',
      'createPullRequest',
    ])
  })

  it('renders dry-run details', async () => {
    const client = new FakeGitHubPrCreationClient()
    const result = await executeGitHubPrCreation(
      { ...request, dryRun: true },
      policy,
      approval,
      client,
    )
    const output = renderGitHubPrCreationResult(result)

    expect(output).toContain('CodeMind GitHub PR creation')
    expect(output).toContain('Outcome: DRY_RUN')
    expect(output).toContain('Dry-run only. No GitHub API call has been made.')
  })
})
